// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Account struct {
	ID             int64
	Email          string
	PasswordHash   string
	FirstName      string
	LastName       string
	ProfilePicture string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Subscription struct {
	ID               int64
	AccountID        int32
	ServiceName      string
	PlanName         string
	BillingFrequency string
	Cost             float64
	Currency         string
	Icon             string
	Active           sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}
